---
- name: Include hostname task
  include_tasks: hostname.yml
  when: enable_hostname

- name: Include powertools task
  include_tasks: powertools.yml
  when: enable_powertools

- name: Include remap_user task
  include_tasks: remap_user.yml
  when: enable_remap_user and ansible_os_family == "RedHat"

- name: Create user task
  include_tasks: create_user.yml
  when: enable_create_user

- name: Include exclude_packages
  include_tasks: exclude_package_from_update.yml
  when: enable_exclude_packages

- name: Include kernel_5 task for RHEL8
  include_tasks: kernel_5.yml
  when: enable_kernel_5 and ansible_os_family == "RedHat" and ansible_distribution_major_version == '8'

- name: Include pam_limits task
  include_tasks: pam_limits.yml
  when: enable_pam_limits

- name: Include grub task
  include_tasks: grub.yml
  when: enable_grub

- name: Include cgroups task
  include_tasks: cgroups.yml
  when: enable_cgroups

- name: Include journald task
  include_tasks: journald.yml
  when: enable_journald

- name: Include install_software task
  include_tasks: install_software.yml
  when: enable_install_software

- name: Include cron task
  include_tasks: cron.yml
  when: enable_ansible_root_cron
