---
# RHEL uses GID 999 and UID 999, both of which need to be
# mapped to the galaxy user and group.

- name: Ensure findutils is installed
  become: true
  ansible.builtin.package:
    name: findutils
    state: installed

- name: Get all groups
  getent:
    database: group
    split: ':'

- name: Get all users
  getent:
    database: passwd
    split: ':'

- name: Remap GID 999 if Galaxy group is not present
  block:
    - name: Check for GID 999 group
      ansible.builtin.shell:
        cmd: grep 999 /etc/group
      register: check_group
      changed_when: false
      failed_when: check_group.rc not in (0, 1)

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: check_group
      when: debug

    - name: Replace in group file
      ansible.builtin.replace:
        path: /etc/group
        regexp: '999'
        replace: "500"
      when: (not ansible_check_mode and check_group.rc == 0 and not check_group.stdout == '')

    - name: Search and replace 999 group files
      ansible.builtin.shell:
        cmd: "find / -mount -gid 999 -exec chgrp 500 '{}' +"
      ignore_errors: true
      when: check_group.rc == 0
      tags:
        - ignore_errors
  when: (not "galaxy" in getent_group.keys())

- name: Remap UID 999 if Galaxy user is not present
  block:
    - name: Check for UID 999 in user file
      ansible.builtin.shell:
        cmd: grep 999 /etc/passwd
      register: check_user
      changed_when: false
      failed_when: check_user.rc not in (0, 1)

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: check_user
      when: debug

    - name: Replace in passwd file
      ansible.builtin.replace:
        path: /etc/passwd
        regexp: '999'
        replace: "500"
        validate: /usr/sbin/pwck %s
      when: (not ansible_check_mode and check_user.rc == 0 and not check_user.stdout == '')

    - name: Search and replace 999 user files
      ansible.builtin.shell:
        cmd: "find / -mount -uid 999 -exec chown 500 '{}' +"
      ignore_errors: true
      when: check_user.rc == 0
      tags:
        - ignore_errors
  when: (not "galaxy" in getent_passwd.keys())
